---
- name: Configure EC2 instance
  hosts: <ec2-instance-ip>
  remote_user: ec2-user
  become: true

  vars:
    app_name: myapp
    app_port: 8000


  tasks:
    - name: Install Python 3 and pip
      yum:
        name: python3
        state: present

    - name: Install pip packages
      pip:
        name:
          - fastapi
          - uvicorn[standard]
          - psycopg2-binary

    - name: Clone FastAPI application code
      git:
        repo: https://github.com/<username>/<repository>.git
        dest: /home/ec2-user/{{ app_name }}
        version: master

    - name: Install pip packages for the application
      pip:
        requirements: /home/ec2-user/{{ app_name }}/requirements.txt

    - name: Start the FastAPI application
      command: uvicorn {{ app_name }}.main:app --host 0.0.0.0 --port {{ app_port }} --workers 4 --log-level warning
      